Adding Avi ansible lookup module
avinetworks/ansible pull request #10
Opened 2019-06-27 10:57 UTC by sandeepavi

Adding new lookup plugin to allow lookups against Avi controller objects

- New Module Pull Request

avi lookup plugin

```paste below

- debug: msg="{{ lookup('avi', obj_type='virtualservice',
    tenant='admin', controller_ip='controller_ip', username='username', password='password') }}"
- debug: msg="{{ lookup('avi', obj_name='vs1', obj_type='virtualservice',
    tenant='admin', controller_ip='controller_ip', username='username', password='password') }}"
- debug: msg="{{ lookup('avi', obj_uuid='virtualservice-5c0e183a-690a-45d8-8d6f-88c30a52550d',
    obj_type='virtualservice', tenant='admin', controller_ip='controller_ip', username='username',

```

2019-06-27 10:59 UTC, sandeepavi commented
Hi @chaitanyaavi , @grastogi23 

Could you please review this PR. I need some help what `session_params` we should skip as mentioned by @grastogi23 in another PR.

Thanks,
Sandeep

2019-06-27 15:58 UTC, grastogi23 requested changes

2019-06-27 15:58 UTC, grastogi23 commented on lib/ansible/plugins/lookup/avi.py
> +                response = [avi.get(obj_path, **get_params).json()]
we need to check for errors. If the avi.get returns error then what happens? How is the error returned.

2019-06-27 15:58 UTC, grastogi23 commented on lib/ansible/plugins/lookup/avi.py
> +            raise AnsibleError("Unable to query the Avi Controller")
Need better error here. There can be other errors like network error, Avi Api error etc. For those what is the error returned.

2019-06-27 15:58 UTC, grastogi23 commented on lib/ansible/plugins/lookup/avi.py
> +                response = [avi.get_object_by_name(path, name, **get_params)]
there is a case when get_object_by_name returns None. we should handle it.

2019-06-27 15:58 UTC, grastogi23 commented on lib/ansible/plugins/lookup/avi.py
> +                'avi_credentials': kwargs.get('avi_credentials', None),
let us only expose avi_credentials as only way to do the lookup as we don't have any legacy code to be compatible with.
Everything else should be done using avi_credentials only.

2019-06-27 15:58 UTC, grastogi23 commented on lib/ansible/plugins/lookup/avi.py
> +            get_params = {
Can we support any parameter that user can send and gets applied. This way parameters like refers_to:xxx will naturally get supported.

2019-07-01 20:33 UTC, grastogi23 commented
@sandeepavi can you please run it via ansible sanity. I think there are formatting issues it would not like

2019-07-02 04:36 UTC, sandeepavi commented
sure @grastogi23. The PR is still in works. I pushed the partial code for backup. Can I add new labels to this repo for signifying things like WIP, DO NOT REVIEW etc.

2019-07-02 06:47 UTC, sandeepavi commented
PR is ready for review. Ran ansible sanity and it passed.

2019-07-02 16:37 UTC, grastogi23 commented
hi let us create pull request to the ansible core...

2019-07-02 16:37 UTC, grastogi23 approved these changes

2019-07-02 21:04 UTC, rfrommer commented
If pointed explicitly to help text fields needing review, I remain ever willing to point out mistakes and areas of improvement.

2019-07-08 05:27 UTC, closed without merging